name: Deploy API to GCP

on:
  workflow_run:
    workflows: ["Deploy Infrastructure to GCP"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev
      - name: Pull model with DVC
        run: |
          pip install dvc-gs
          poetry run dvc pull app/model/red_wine_model.pkl
      - name: Build and push Docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/wine-quality-prediction-api/wine-quality-prediction-api:latest -f Dockerfile.api .
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/wine-quality-prediction-api/wine-quality-prediction-api:latest

      - name: Deploy to Compute Engine via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            echo '${{ secrets.GCP_SA_KEY }}' > ~/gcp-sa-key.json
            sudo gcloud auth activate-service-account --key-file ~/gcp-sa-key.json --quiet
            ACCESS_TOKEN=$(gcloud auth print-access-token)
            sudo docker login -u oauth2accesstoken -p "$ACCESS_TOKEN" https://europe-west1-docker.pkg.dev
            sudo docker pull europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/wine-quality-prediction-api/wine-quality-prediction-api:latest
            sudo docker stop wine-quality-prediction-api || true
            sudo docker rm wine-quality-prediction-api || true
            sudo docker run -d -p 80:8000 --name wine-quality-prediction-api europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/wine-quality-prediction-api/wine-quality-prediction-api:latest
